repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.5.4
      hooks:
          - id: autopep8
            language_version: python3
            args:
                [
                    '--in-place',
                    '--ignore',
                    'E402,E203',
                    '--max-line-length',
                    '79',
                    '--experimental',
                    '--exclude',
                    '.*.ipynb',
                ]

    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
            name: isort
            language_version: python3
            args: ['--profile', 'black', '--line-length=79']
